language: ruby
script:
  - "rake test"
  - "gem build arel-fulltext.gemspec"
install:
  - "gem install arel"
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx512M'
rvm:
  - rbx
  - jruby-head
  - 2.0.0
  - 2.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  email: true